title: UnixFriends
author: Martin Chikadaya
description: UNIX is user friendly. It’s just very particular about who its friends are.
google_analytics: true
theme: jekyll-theme-hacker

# Plugins
plugins:
  - jekyll-paginate

# Pagination settings (optional, if using jekyll-paginate)
paginate: 5 # Number of posts per page

# Custom navigation links (optional)
nav_links:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact

# Social media links (optional)
social:
  - title: Whatsapp
    url: https://wa.me/+263713302120
  - title: GitHub
    url: https://github.com/Martinez047

# Footer text (optional)
footer_text: "Copyright © 2024 Chikadaya Martin"
