title: UnixFriends
author: Martin Chikadaya
description: UNIX is user friendly. It’s just very particular about who its friends are.
google_analytics: true
theme: jekyll-theme-hacker
google_analytics: G-4C7EJJPYT1

# Plugins
plugins:
  - jekyll-paginate

# Pagination settings (optional, if using jekyll-paginate)
paginate: 5 # Number of posts per page

# Social media links 
social:
  - title: Whatsapp
    url: https://wa.me/+263713302120
  - title: GitHub
    url: https://github.com/Martinez047

# Footer text 
footer_text: "Copyright © 2024 Chikadaya Martin"
